### VALUES YOU SHOULD CHANGE ###

# GENERAL SITE SETTINGS
# title: This will be displayed as the website's name in your browser tab.
title: Dheeraj Jha
# description: This will be meta HTML tag content. This can be ignored.
description: Personal website powered by Jekyll
# baseurl: The subpath of your site
# > set this to "", if you renamed the repository to <user>.github.io
baseurl: ""
# baseurl: "/neumorphism"

# LANDING PAGE
# username: This will displayed on the landing page as your name.
username: DheerajJha
# typing_text: This will be typed before 'scroll down for more'.
# > set this to your job title, e.g. Fullstack Developer
typing_text: Student by nature, Software Engineer by profession.
# email: Your E-Mail address for the email button.
email: contact@jhadheeraj.com
# For every social button you want to display, set your username or userid
# If you do not use one of the following websites, then leave it empty
# > twitter_username:
github_username: jhadheeraj1986
# codepen_username: exampleUser
# dev_username: exampleUser
linkedin_username: jhadheeraj
twitter_username: dheerajjha03
youtube_username: Programming_Gyan
personal_blog: https://programminggyan.com/

# ABOUT ME SECTION
# show_aboutme_card:
# > setting this to true, will display the About Me section
# > setting this to false, will omit the About Me section
show_aboutme_card: true
# about_me_title: The will be displayed as the title in the About Me section
about_me_title: More about me
# about_me_description: This will be displayed under the title.
about_me_description: Meet <span style="color:red;font-weight:bold">Dheeraj Jha</span>, a highly skilled and passionate <span style="color:red;font-weight:bold">software engineer with almost 13 years of experience</span> in the IT industry. Based in <span style="color:red;font-weight:bold">Bangalore</span>, India, <span style="color:deepskyblue;font-style:italic">Dheeraj is a student at heart and a Tech Lead by profession</span>.<br><br> Dheeraj's core skills lie in C++ <span style="color:red;font-weight:bold">(11/14/17)</span>, and he also has experience with <span style="color:red;font-weight:bold">Python</span>. He is currently expanding his skill set by learning new programming languages like Rust. He has extensive experience in <span style="color:red;font-weight:bold">designing and developing software products</span>, with a keen interest in <span style="color:red;font-weight:bold">Cloud and Security technologies</span>. Dheeraj is certified as an <span style="color:red;font-weight:bold">AWS Architect - Associate</span> and is currently studying Cyber Security.<br><br> Dheeraj has worked in diverse domains such as finance, security, automotive, and IoT. In his current role, he is involved in <span style="color:red;font-weight:bold">developing an IoT product</span> and is <span style="color:deepskyblue;font-style:italic">responsible for all stages of the SDLC lifecycle, showcasing his expertise in requirement gathering and transforming those requirements into a product</span>. He is <span style="color:red;font-weight:bold">the lead engineer</span> in his current project for designing (System as well as LLD) and managing the development.<br><br> Dheeraj is a versatile developer with a strong foundation in <span style="color:red;font-weight:bold">Object-Oriented Programming concepts</span>, <span style="color:red;font-weight:bold">data structures</span>, <span style="color:red;font-weight:bold">multi-threading</span>, and <span style="color:red;font-weight:bold">system programming</span>. He is proficient in different OS platforms like Linux & Windows and database management in <span style="color:red;font-weight:bold">MySQL</span> and <span style="color:red;font-weight:bold">SQL Server</span>. He is also skilled in scripting languages like <span style="color:deepskyblue;font-style:italic">Python</span> and <span style="color:deepskyblue;font-style:italic">JavaScript</span>, and <span style="color:deepskyblue;font-style:italic">well-versed in front-end technologies</span> like HTML, CSS, and JSON.<br><br> In addition to his technical skills, Dheeraj is knowledgeable in various <span style="color:red;font-weight:bold">design patterns and networking fundamentals</span>. He has also gained experience with cloud services like <span style="color:red;font-weight:bold">AWS</span> and IoT technologies like <span style="color:deepskyblue;font-style:italic">MQTT</span> and <span style="color:deepskyblue;font-style:italic">Raspberry Pi</span>. Source control tools such as <span style="color:red;font-weight:bold">SVN</span> and <span style="color:red;font-weight:bold">Git</span>, as well as reporting and task management platforms like <span style="color:red;font-weight:bold">JIRA</span> and Redmine, are also part of his toolkit.<br><br> Dheeraj has demonstrated his <span style="color:red; font-weight:bold;">leadership skills</span> by conducting <span style="color:red; font-weight:bold;">in-depth code reviews</span> and <span style="color:red; font-weight:bold;">mentoring a team</span>, ensuring their work meets high standards. He has also successfully <span style="color:red; font-weight:bold;">collaborated with business</span> and <span style="color:red; font-weight:bold;">subject matter experts</span> to translate requirements into technical solutions. With a solid understanding of <span style="color:red; font-weight:bold;">business modeling</span>, <span style="color:red; font-weight:bold;">SDLC processes</span>, and <span style="color:red; font-weight:bold;">performance tuning</span>, Dheeraj has demonstrated his ability to contribute to the <span style="color:red; font-weight:bold;">design and implementation of successful solutions</span>.<br><br> Dheeraj holds a <span style="color:skyblue; font-style:italic;">B.Tech</span> degree in <span style="color:skyblue; font-style:italic;">Electronics and Communication</span> and a <span style="color:skyblue; font-style:italic;">Post Graduate Diploma in System software Development from CDAC-ACTS, Pune</span>.<br><br> Apart from his technical expertise, Dheeraj is also an advocate of the philosophy that <span style="color:skyblue; font-style:italic;">you learn more when you teach</span>. He founded <a class="highlight-link" href="https://www.cppindia.co.in/" target="_blank" rel="noreferrer"> <span style="color:skyblue; font-style:italic;">CppIndia</span> </a>, <span style="color:skyblue; font-style:italic;">an active online C++ community in India</span>, where experienced professionals, fresh graduates, college students, and recruiters come together on a single platform. The community has gained recognition from international communities like <span style="color:skyblue; font-style:italic;">ISOCpp.org</span> and <span style="color:skyblue; font-style:italic;">CppCon</span>. CppIndia is a free community where members can attend talks and engage with industry experts. Be sure to check out their <span style="color:red; font-weight:bold;">YouTube channel</span> and join the <span style="color:red; font-weight:bold;">discord community</span> if you're interested!<br><br> Dheeraj may not be great at technical writing, but he's working on improving his skills through his personal blog. Dheeraj is also building a blogging platform where people like him can write their blogs under the brand name <a class="highlight-link" href="https://programminggyan.com/" target="_blank" rel="noreferrer"><span style="color:skyblue; font-style:italic;">ProgrammingGyan</span></a>.<br><br> Outside of work, Dheeraj enjoys gardening and DIY projects and has a passion for photography, capturing beautiful moments with his trusty Nikon. He also loves reading self-help and startup books, in addition to technical ones.<br><br> With his technical prowess and leadership skills, Dheeraj is an ideal candidate for any organization looking for a passionate software engineer who can make a positive difference.<br><br>
# Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. If you like this theme and want to use it for yourself, checkout the source code and the documentation at <a class="highlight-link" href="https://github.com/longpdo/neumorphism" target="_blank" rel="noreferrer"> Github </a>. You can also find me on <a class="highlight-link" href="https://jamstackthemes.dev/theme/jekyll-neumorphism/" target="_blank" rel="noreferrer">JAMstack Themes</a> and on <a class="highlight-link" href="https://jekyll-themes.com/neumorphism/" target="_blank" rel="noreferrer">Jekyll Themes</a>.
# <a class="highlight-link" href="https://github.com/longpdo/neumorphism" target="_blank" rel="noreferrer"> Github </a>

# SKILLS SECTION
# show_skills_card:
# > setting this to true, will display the Skills section
# > setting this to false, will omit the Skills section
show_skills_card: true
# about_me_title: The will be displayed as the title in the Skills section
skills_title: Skills

# TIMELINE SECTION
# show_timeline_card:
# > setting this to true, will display the Timeline section
# > setting this to false, will omit the Timeline section
show_timeline_card: true
# timeline_title: The will be displayed as the title in the Timeline section
timeline_title: Education & Experience
# cv_download_link: The link where you host your cv.
# > e.g. you share your cv on your dropbox, then add the dropbox link here
cv_download_link: /mydocs/Dheeraj Jha.pdf

# PROJECTS SECTION
# show_projects_card:
# > setting this to true, will display the Projects section
# > setting this to false, will omit the Projects section
show_projects_card: true
# show_projects:
# > setting this to true, will display your listed projects in _data/projects.yml
# > setting this to false, will omit your listed projects
show_projects: true
# projects_title: The will be displayed as the title of your projects
projects_title: Projects
# show_os_projects:
# > setting this to true, will display your public projects on github
# > setting this to false, will omit your public projects on github
show_os_projects: false
# os_projects_title: The will be displayed as the title of your open source projects
os_projects_title: Open Source Projects

# CONTACT SECTION
# show_contact_card:
# > setting this to true, will display the Contact section
# > setting this to false, will omit the Contact section
show_contact_card: true
# contact_title: The will be displayed as the title in the Contact section
contact_title: Contact
# contact_description: This will be displayed under the title.
contact_description: If you would like to get in touch with me, there are a few ways you can do so. You can send an email to <a href="mailto:contact@jhadheeraj.com">contact@jhadheeraj.com</a> and I will get back to you as soon as possible. Alternatively, you can find me on LinkedIn or Twitter. Feel free to send me a message or connect with me on these platforms. I'm always happy to hear from people and to have a conversation about anything related to technology, programming, or other interests we might share.

show_youtube_card: false
youtube_title: YouTube
youtube_description: Talk's given by Dheeraj Jha.

# GITHUB-METADATA
# Set this to your forked repository
# > e.g. <user>/<user>.github.io
repository: jhadheeraj1986/dheeraj_jha
projects:
  # sortby:
  # > set this to pushed, if you want to sort your github repositories by time.
  # > set this to stars, if you want to sort your github repositories by stars.
  sort_by: pushed
  exclude:
    # archived:
    # > setting this to true, will exclude archived repositories
    # > setting this to false, will also display archived repositories
    archived: true
    # forks:
    # > setting this to true, will exclude forked repositories
    # > setting this to false, will also display forked repositories
    forks: true
    # projects: A list of the repository names you want to exclude from the listing.
    projects:
    # - repo1-to-be-excluded
    # - repo2-to-be-excluded

# GOOGLE-ANALYTICS
# Set the id, if you want to track your website with Google Analytics
# > set this to "", if you do not want to track with Google Analytics
google-analytics:
  id: "UA-158757509-2"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
